export const MOCK_STUDENTS_LISTS = [
  {
    id: 1,
    name: '2023년 9월 명단',
    students: [
      { number: 1, name: '김김학생' },
      { number: 2, name: '이이학생' },
      { number: 3, name: '박박학생' },
      { number: 4, name: '우우학생' },
      { number: 5, name: '최최학생' },
      { number: 6, name: '조조학생' },
      { number: 7, name: '장장학생' },
      { number: 8, name: '나나학생' },
      { number: 9, name: '다다학생' },
      { number: 10, name: '가가학생' },
      { number: 11, name: '고고학생' },
      { number: 12, name: '라라학생' },
      { number: 13, name: '마마학생' },
      { number: 14, name: '바바바학생' },
      { number: 15, name: '사학생' },
      { number: 16, name: '아하학생' },
      { number: 17, name: '하하학생' },
    ],
  },
  {
    id: 2,
    name: '2023년 10월 명단',
    students: [
      { number: 1, name: '김나라' },
      { number: 2, name: '이나라' },
      { number: 3, name: '박나라' },
      { number: 4, name: '우나라' },
      { number: 5, name: '최나라' },
      { number: 6, name: '조나라' },
      { number: 7, name: '장나라' },
      { number: 8, name: '나나라' },
      { number: 9, name: '다나라' },
      { number: 10, name: '가나라' },
    ],
  },
];
